import React from 'react';
import { motion } from 'framer-motion';
import { 
  FiZap, FiSmartphone, FiShield, FiClock, 
  FiBarChart2, FiEye, FiFileText, FiSend,
  FiActivity, FiLock, FiTrendingUp, FiPieChart,
  FiSettings, FiUsers, FiGlobe, FiCpu,
  FiCloud, FiKey, FiCompass, FiMonitor, FiRepeat, FiArrowRight
} from 'react-icons/fi';

const Features = ({ onTry }) => {
  const featureList = [
    { 
      title: 'Real-Time Performance Engine', 
      desc: 'Powered by Lighthouse, providing millisecond-accurate metrics for LCP, CLS, and FCP.',
      icon: <FiZap />,
      tier: 'Free'
    },
    { 
      title: 'Mobile Device Emulation', 
      desc: 'Simulate high-end and low-end mobile devices with network throttling.',
      icon: <FiSmartphone />,
      tier: 'Pro'
    },
    { 
      title: 'Deep Security Audit', 
      desc: 'Detailed checks for HSTS, CSP, X-Frame-Options, and SSL health.',
      icon: <FiShield />,
      tier: 'Pro'
    },
    { 
      title: 'AI Optimization Assistant', 
      desc: 'Context-aware code snippets generated by AI to fix performance bottlenecks.',
      icon: <FiZap />,
      tier: 'Free'
    },
    { 
      title: 'Resource Weight Analysis', 
      desc: 'Detailed breakdown of JS, CSS, Images, and Font weights.',
      icon: <FiBarChart2 />,
      tier: 'Pro'
    },
    { 
      title: 'Historical Trends', 
      desc: 'Track your performance score over time with interactive line charts.',
      icon: <FiTrendingUp />,
      tier: 'Pro'
    },
    { 
      title: 'Side-by-Side Comparison', 
      desc: 'Compare any two analysis reports to see the impact of your changes.',
      icon: <FiRepeat />,
      tier: 'Pro'
    },
    { 
      title: 'Professional PDF Reports', 
      desc: 'Generate branded, presentation-ready PDF reports for clients.',
      icon: <FiPieChart />,
      tier: 'Pro'
    },
    { 
      title: 'Social Preview Audit', 
      desc: 'See exactly how your site appears on Google, Facebook, and Twitter.',
      icon: <FiEye />,
      tier: 'Pro'
    },
    { 
      title: 'Developer API Keys', 
      desc: 'Integrate SpeedGenius metrics directly into your CI/CD pipeline.',
      icon: <FiKey />,
      tier: 'Enterprise'
    },
    { 
      title: 'Slack & Discord Integration', 
      desc: 'Get instant alerts when your performance drops below a threshold.',
      icon: <FiSend />,
      tier: 'Enterprise'
    },
    { 
      title: 'Global Edge Analysis', 
      desc: 'Run audits from over 50+ global locations for real-world TTFB metrics.',
      icon: <FiGlobe />,
      tier: 'Enterprise'
    }
  ];

  return (
    <div className="container" style={{ padding: '6rem 0' }}>
      <div style={{ textAlign: 'center', marginBottom: '5rem' }}>
        <h1 className="gradient-text" style={{ fontSize: '3.5rem', marginBottom: '1.5rem' }}>Everything You Need to Scale</h1>
        <p style={{ color: 'var(--text-secondary)', fontSize: '1.25rem', maxWidth: '600px', margin: '0 auto' }}>
          Over 20+ premium features designed for modern web performance engineers.
        </p>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(350px, 1fr))', gap: '2rem' }}>
        {featureList.map((feature, idx) => (
          <motion.div
            key={idx}
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: idx * 0.05 }}
            className="glass glass-hover"
            style={{ padding: '2.5rem', display: 'flex', flexDirection: 'column' }}
          >
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '1.5rem' }}>
              <div style={{ background: 'rgba(255,255,255,0.03)', padding: '1rem', borderRadius: '15px', color: 'var(--accent-blue)', fontSize: '1.5rem' }}>
                {feature.icon}
              </div>
              <span className={`badge ${feature.tier === 'Free' ? '' : 'badge-pro'}`}>
                {feature.tier}
              </span>
            </div>
            <h3 style={{ fontSize: '1.25rem', marginBottom: '1rem' }}>{feature.title}</h3>
            <p style={{ color: 'var(--text-secondary)', fontSize: '0.95rem', lineHeight: '1.6', marginBottom: '2rem', flex: 1 }}>{feature.desc}</p>
            
            <button 
              onClick={() => onTry(feature)}
              className="btn-secondary" 
              style={{ width: '100%', justifyContent: 'center', gap: '0.5rem', fontSize: '0.85rem', padding: '0.75rem' }}
            >
              Try Now <FiArrowRight size={14} />
            </button>
          </motion.div>
        ))}
      </div>
    </div>
  );
};

export default Features;
